name: potato_disease_detection
description: A Flutter app for potato disease classification using AI
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0' # ✅ Dart 3.8+ for latest packages

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.2.1
  image_picker: ^1.1.2
  file_picker: ^6.2.0 # ✅ stable version compatible with web & desktop
  path: ^1.9.0
  image: ^4.2.0

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0 # ✅ requires Dart >=3.8

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"
